### ISSUE TITLE
Exclude a particular field by id

### ISSUE THREAD

**Issue by snaphow** [fengyuanchen/formcache#4]
Is it possible to exclude a particular field by id. That will be very useful...

**Comment by fengyuanchen** [comment]
Set `controls` option: Just add the form controls what you want to cache .

**Comment by snaphow** [comment]
Actually the fields are dynamic... But there is one fixed field I wanted not to cache, I was hoping if there is a possibility.

**Comment by fengyuanchen** [comment]
Sorry, we don't support it. But you can try to implement it.
