### ISSUE TITLE
Hook that gives access to serialized object prior to setting from values

### ISSUE THREAD

**Issue by NotMyself** [fengyuanchen/formcache#6]
I have a form that contains dynamically created inputs. Is it possible to get a hook that allows me to inspect the serialized object to add the dynamic inputs prior to setting form values?

**Comment by fengyuanchen** [comment]
Prepare all form controls before start a formcahe and store cache object manually before unload the page.

```js
// 1. Prepare form controls

// 2. Call the plugin
$('form').formcache({
  autoStore: false
});

// 3. Cache data manually
$('form').formcache('store');

// 4. Destory the plugin
$('form').formcache('destory');

// 5. => 1.
//...
```

**Comment by NotMyself** [comment]
In this case I need to know the state of the form cache to set up the form. Here is an example of what I am talking about:

![dynamic_fields](https://cloud.githubusercontent.com/assets/73120/7963783/4e7e2086-09c9-11e5-9055-5f6619a4f84b.PNG)


**Note:** the add buttons dynamically add form elements to the form.

**Comment by fengyuanchen** [comment]
You can cache the form states manually before submitting the form, and get the cache data when reload the page, filter the data, check how many form controls there are, then add those form controls dynamically, then fill them with the cache data.
