### ISSUE TITLE
Setup PATH to save

### ISSUE THREAD

**Issue by dzung1nguyen** [fengyuanchen/formcache#7]
Hi Guy,

Before, i am thank so much for your plugin, It work nice.

I have a issue:
I go to path: /abc/register
In that have a form but have 4 steps
step 1: /abc/register/getting
step 2: /abc/register/basic
step 3: /abc/register/extended
step 4: /abc/register/personal

If i open step 1 and enter input ... then i open step 2 => data at step 1 does not display.

How to i save form and can use it for 4 steps?

Thanks.

**Comment by fengyuanchen** [comment]
Setp 1: `$('form').formcache('setCache', 0, $('form').formcache('serialize'))`
Setp 2: `$('form').formcache('setCache', 1, $('form').formcache('serialize'))`
Setp 3: `$('form').formcache('setCache', 2, $('form').formcache('serialize'))`
Setp 4: `$('form').formcache('setCache', 3, $('form').formcache('serialize'))`
