### ISSUE TITLE
Delete the cache after submit

### ISSUE THREAD

**Issue by robinbirr** [fengyuanchen/formcache#9]
How can i delete destroy the caches after submit the form?

**Comment by fengyuanchen** [comment]
After submitted the form:

```js
$('form').formcache('clear').formcache('destroy');
```

**Comment by robinbirr** [comment]
Ok, and how can i call this function?
As onclick Event on the submit button?
`onclick="(function($){$(function () {$('form').formcache('clear').formcache('destroy');});});"`
